services:
  app:
    build:
      context: .
    container_name: my_app
    ports:
      - "${APP_PORT:-8888}:8888"
    environment:
      # Дефлолтный read-write датасорс
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      # Датасорс на запросы чтения при работе с постами
      SPRING__READ_ONLY_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING__READ_ONLY_DATASOURCE_USERNAME: postgres
      SPRING__READ_ONLY_DATASOURCE_PASSWORD: postgres

      # Датасорс на запросы для работы с диалогами
      SPRING_SHARDING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_SHARDING_DATASOURCE_USERNAME: postgres
      SPRING_SHARDING_DATASOURCE_PASSWORD: postgres

    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "${POSTGRES_PORT:-5440}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 1s
      timeout: 5s
      retries: 5

