global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'app'
    static_configs:
      - targets: ['host.docker.internal:8888']  # Указываем только хост и порт
    metrics_path: '/actuator/prometheus'  # Полный путь к метрикам
