version: '3.8'

# Для возможности использования "network-mode=host" в Docker-Desktop необходимо включать галку

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    network_mode: "host"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: adminpassword
    network_mode: "host"
    expose:
      - 3000
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
  prometheus_data: