version: '3'
services:
  postgres-microservice:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5440:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 1s
      timeout: 5s
      retries: 5

  microservice:
    build:
      context: .
    ports:
      - "${APP_PORT:-8888}:8889"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-microservice:5432/mydatabase
    depends_on:
      postgres-microservice:
        condition: service_healthy
