server:
  port: 8888

spring:
  datasource:
    # датасорс необязателен (если указан, то на нём выполняются только read-only транзакции)
    read-only:
      url: ${SPRING_READ_ONLY_DATASOURCE_URL:jdbc:postgresql://localhost:5438/mydatabase}
      username: ${SPRING_READ_ONLY_DATASOURCE_USERNAME:postgres}
      password: ${SPRING_READ_ONLY_DATASOURCE_PASSWORD:postgres}
      driver-class-name: org.postgresql.Driver

    # дефолтный датасорс (если указан read-only, то на read-write только write транзакции, иначе все)
    read-write:
      url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5438/mydatabase}
      username: ${SPRING_DATASOURCE_USERNAME:postgres}
      password: ${SPRING_DATASOURCE_PASSWORD:postgres}
      driver-class-name: org.postgresql.Driver

  # использует дефолтный датасорс
  flyway:
    enabled: true
    table: schema_history

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

springdoc:
  api-docs:
    # доступ к OpenAPI
    path: /api-docs
  swagger-ui:
    # доступ к swagger
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.hibernate.SQL: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
