version: '3.8'

services:
  influxdb2:
    image: influxdb:2
    container_name: influxdb2
    ports:
      - "8086:8086"  # Порт для доступа к InfluxDB
    volumes:
      - influxdb2_data:/var/lib/influxdb2  # Хранение данных
      # - influxdb2-config:/etc/influxdb2  # Хранение конфигурации (если необходимо)
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=ADMIN_USERNAME
      - DOCKER_INFLUXDB_INIT_PASSWORD=ADMIN_PASSWORD
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=MyInitialAdminToken0==
      - DOCKER_INFLUXDB_INIT_ORG=ORG_NAME
      - DOCKER_INFLUXDB_INIT_BUCKET=BUCKET_NAME

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - influxdb2
    environment:
      GF_SECURITY_ADMIN_PASSWORD: adminpassword
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  influxdb2_data:
  grafana_data:

