{
 "title": "Latency Before",
 "time": { "from": "2025-03-24T22:18:58.003Z", "to": "2025-03-24T22:20:19.476Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"jmeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"requestName\"] == \"Search\" )\n  |> filter(fn: (r) => r._measurement == \"requestsRaw\" and r.responseCode == \"200\" and r._field == \"latency\")\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> map(fn: (r) => ({ r with Search: r._value }))\n  |> drop(columns: [\"_value\"])\n  |> yield(name: \"Mean Latency\")"
    },
    {
     "query": "from(bucket: \"jmeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"requestName\"] == \"GetUser\" )\n  |> filter(fn: (r) => r._measurement == \"requestsRaw\" and r.responseCode == \"200\" and r._field == \"latency\")\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> map(fn: (r) => ({ r with GetUser: r._value }))\n  |> drop(columns: [\"_value\"])\n  |> yield(name: \"Mean Latency\")"
    }
   ]
  },
  {
   "title": "Throughput (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"jmeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"requestName\"] == \"Search\"  )\n  |> filter(fn: (r) => r._measurement == \"requestsRaw\" and r.responseCode == \"200\" and r._field == \"latency\")\n  |> aggregateWindow(every: 1s, fn: count, createEmpty: false)\n  |> map(fn: (r) => ({ r with Search: r._value }))\n  |> drop(columns: [\"_value\"])\n  |> keep(columns: [\"_time\", \"Search\"])\n  "
    },
    {
     "query": "from(bucket: \"jmeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"requestName\"] == \"GetUser\"  )\n  |> filter(fn: (r) => r._measurement == \"requestsRaw\" and r.responseCode == \"200\" and r._field == \"latency\")\n  |> aggregateWindow(every: 1s, fn: count, createEmpty: false)\n  |> map(fn: (r) => ({ r with GetUser: r._value }))\n  |> drop(columns: [\"_value\"])\n  |> keep(columns: [\"_time\", \"GetUser\"])\n  "
    }
   ]
  },
  {
   "title": "Error count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"jmeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"requestName\"] == \"Search\"  )\n  |> filter(fn: (r) => r._measurement == \"requestsRaw\" and r.responseCode != \"200\" and r._field == \"latency\")\n  |> aggregateWindow(every: 1s, fn: count, createEmpty: false)\n  |> map(fn: (r) => ({ r with Search: r._value }))\n  |> drop(columns: [\"_value\"])\n  |> keep(columns: [\"_time\", \"Search\"])\n  "
    },
    {
     "query": "from(bucket: \"jmeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"requestName\"] == \"GetUser\"  )\n  |> filter(fn: (r) => r._measurement == \"requestsRaw\" and r.responseCode != \"200\" and r._field == \"latency\")\n  |> aggregateWindow(every: 1s, fn: count, createEmpty: false)\n  |> map(fn: (r) => ({ r with GetUser: r._value }))\n  |> drop(columns: [\"_value\"])\n  |> keep(columns: [\"_time\", \"GetUser\"])\n  "
    }
   ]
  }
 ]
}